camunda:
    bpm:
        auto-deployment-enabled: true
        default-serialization-format: application/json
        job-execution:
            deployment-aware: true
            enabled: true
            max-wait: 2000
            wait-time-in-millis: 1000
        process-engine-name: process_solution_2
        database:
            schema-update: false
    generic-properties:
        properties:
            historyTimeToLive: P100D
