spring:
    datasource:
        url: jdbc:h2:tcp://localhost:8089/mem:camunda
        type: org.h2.jdbcx.JdbcDataSource
        driver-class-name: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
            path: /h2
