camunda:
    bpm:
        default-serialization-format: application/json
        job-execution:
            deployment-aware: true
            enabled: true
        database:
            schema-update: false
    generic-properties:
        properties:
            historyTimeToLive: P100D

server:
    port: 8080
