camunda:
    bpm:
        default-serialization-format: application/json
        job-execution:
            deployment-aware: true
            enabled: true
        database:
            schema-update: false

server:
    port: 8080
