camunda.bpm.client:
  base-url: http://localhost:8090/engine-rest
  lock-duration: 10000
  async-response-timeout: 30000

logging:
  level:
    de.rnschk: debug
    org.camunda.bpm.client: debug
    root: warn

de:
  viadee:
    bpm:
      camunda:
        external-task:
          retry-config:
            default-behavior: R0/PT1M
