server:
    port: 8080
camunda:
    bpm:
        admin-user:
            id: fr
            password: foo
            first-name: Florian
            last-name: viadee
        default-serialization-format: application/json
        database:
            schema-update: false
        filter:
            create: All
        job-execution:
            deployment-aware: true
            enabled: true
            max-wait: 1000
            wait-time-in-millis: 500
        login:
            enabled: true
            user-id: fr
        generic-properties:
            properties:
                historyTimeToLive: P100D
de:
    rnschk:
        bpm:
            camunda-branding:
                button-color: '#34568b'
                enabled: true
                top-color: '#88b04b'
logging:
    level:
        root: error
        de:
            rnschk: info
